SELECT CONSIGNMENT.Id, CONSIGNMENT.CustomerCountry, CONSIGNMENT.ZipCode, CONSIGNMENT.Consignmentstatus, CONSIGNMENT.ReportingStatus, MUSICPRODUCT.Id, MUSICPRODUCT.Price, MUSICPRODUCT.ProductDescriptionId
FROM CONSIGNMENT, MUSICPRODUCT_CONSIGNMENT, MUSICPRODUCT
where Consignment.Id = MUSICPRODUCT_CONSIGNMENT.ConsignmentId AND MUSICPRODUCT.Id = MUSICPRODUCT_CONSIGNMENT.ProductId