drop database MusicGlue
go
CREATE DATABASE MusicGlue
go
use MusicGlue

CREATE TABLE REPORTINGORGANISATION (
Id Int IDENTITY(1,1),  
Name NVarChar(50) NOT NULL,
Country NVarChar(50) NOT NULL,

CONSTRAINT PK_REPORTINGORGANISATION PRIMARY KEY (Id)
);

CREATE TABLE CONSIGNMENT (
Id Int IDENTITY(1,1),
CustomerCountry NVarChar(50) NOT NULL,
ZipCode NVarChar(50) NOT NULL,
ConsignmentStatus Int NOT NULL,
ReportingStatus Bit NOT NULL,

CONSTRAINT PK_CONSIGNMENT PRIMARY KEY(Id)
);

CREATE TABLE PRODUCTDESCRIPTION (
Id Int IDENTITY(1,1),
APN NVarChar(50) NOT NULL,
CatalogNumber NVarChar(50) NOT NULL,
SKU NVarCHar(50) NOT NULL,
Barcode NVarChar(50) NOT NULL,

CONSTRAINT PK_PRODUCTDESCRIPTION PRIMARY KEY(Id)
);

CREATE TABLE MUSICPRODUCT (
Id Int IDENTITY(1,1),
Price Float NOT NULL,
ProductDescriptionId Int NOT NULL,

CONSTRAINT PK_MUSICPRODUCT PRIMARY KEY (Id),
CONSTRAINT FK_MUSICPRODUCT_PRODUCTDESCRIPTION FOREIGN KEY (ProductDescriptionId) REFERENCES PRODUCTDESCRIPTION(Id)
);

CREATE TABLE MUSICPRODUCT_CONSIGNMENT (
Id Int IDENTITY(1,1),
ProductId Int NOT NULL,
ConsignmentId Int NOT NULL,

CONSTRAINT PK_MUSICPRODUCTCONSIGMENT PRIMARY KEY (Id),
CONSTRAINT FK_MUSICPRODUCTCONSIGNMENT_MUSICPRODUCT FOREIGN KEY (ProductId) REFERENCES MUSICPRODUCT(Id),
CONSTRAINT FK_MUSICPRODUCTCONSIGNMENT_CONSIGNMENT FOREIGN KEY (ConsignmentId) REFERENCES CONSIGNMENT(Id)
);