DROP DATABASE IF EXISTS MusicGlue;
GO;
CREATE DATABASE MusicGlue;
GO;
USE MusicGlue;
GO;

CREATE TABLE REPORTINGORGANISATION (
	Id INT IDENTITY(1,1),  
	Name NVarChar(50) NOT NULL,
	Country NVarChar(50) NOT NULL,

	CONSTRAINT PK_REPORTINGORGANISATION PRIMARY KEY (Id)
);

CREATE TABLE REPORT (
	Id INT IDENTITY(1,1),
	FileName NVarChar(200) NOT NULL, 
	ReportingDate DateTime2 NOT NULL,
	TotalSales INT NOT NULL,
	ReportStatus INT NOT NULL,
	ReportingOrganisationId INT,

	CONSTRAINT PK_REPORT PRIMARY KEY(Id),
	CONSTRAINT FK_REPORT_REPORTINGORGANISATION FOREIGN KEY (ReportingOrganisationId) REFERENCES REPORTINGORGANISATION(Id) 
);


CREATE TABLE CONSIGNMENT (
	Id INT IDENTITY(1,1),
	CustomerCountry NVarChar(50) NOT NULL,
	ZipCode NVarChar(50) NOT NULL,
	ConsignmentStatus INT NOT NULL,
	ReportingStatus INT NOT NULL,

	CONSTRAINT PK_CONSIGNMENT PRIMARY KEY(Id)
);

CREATE TABLE REPORT_CONSIGNMENT (
	ReportId INT,
	ConsignmentId INT 

	CONSTRAINT PK_REPORTCONSIGNMENT PRIMARY KEY(ReportId,ConsignmentId),
	CONSTRAINT FK1_REPORTCONSIGNMENT_REPORT FOREIGN KEY (ReportId) REFERENCES REPORT(Id),
	CONSTRAINT FK2_REPORTCONSIGNMENT_CONSIGNMENT FOREIGN KEY (ConsignmentId) REFERENCES CONSIGNMENT(Id)
);

CREATE TABLE PRODUCTDESCRIPTION (
	Id INT IDENTITY(1,1),
	APN NVarChar(50) NOT NULL,
	CatalogNumber NVarChar(50) NOT NULL,
	SKU NVarCHar(50) NOT NULL,
	Barcode NVarChar(50) NOT NULL,

	CONSTRAINT PK_PRODUCTDESCRIPTION PRIMARY KEY(Id)
);

CREATE TABLE MUSICPRODUCT (
	Id INT IDENTITY(1,1),
	Price Float NOT NULL,
	ProductDescriptionId Int NOT NULL,

	CONSTRAINT PK_MUSICPRODUCT PRIMARY KEY (Id),
	CONSTRAINT FK_MUSICPRODUCT_PRODUCTDESCRIPTION FOREIGN KEY (ProductDescriptionId) REFERENCES PRODUCTDESCRIPTION(Id)
);

CREATE TABLE MUSICPRODUCT_CONSIGNMENT (
	Id INT IDENTITY(1,1),
	ProductId INT NOT NULL,
	ConsignmentId INT NOT NULL,

	CONSTRAINT PK_MUSICPRODUCTCONSIGMENT PRIMARY KEY (Id),
	CONSTRAINT FK_MUSICPRODUCTCONSIGNMENT_MUSICPRODUCT FOREIGN KEY (ProductId) REFERENCES MUSICPRODUCT(Id),
	CONSTRAINT FK_MUSICPRODUCTCONSIGNMENT_CONSIGNMENT FOREIGN KEY (ConsignmentId) REFERENCES CONSIGNMENT(Id)
);

GO;

