CREATE PROCEDURE spSelectConsignmentsJoinMusicProductsAndProudctDescription AS
BEGIN
	SELECT
		CONSIGNMENT.Id AS 'ConsignmentId', 
		CONSIGNMENT.CustomerCountry, 
		CONSIGNMENT.ZipCode, 
		CONSIGNMENT.ConsignmentStatus, 
		CONSIGNMENT.ReportingStatus,
		MUSICPRODUCT.Id AS 'MusicProductId', 
		MUSICPRODUCT.Price,
		PRODUCTDESCRIPTION.Id AS 'ProductDescriptionId', 
		PRODUCTDESCRIPTION.APN, 
		PRODUCTDESCRIPTION.CatalogNumber, 
		PRODUCTDESCRIPTION.SKU, 
		PRODUCTDESCRIPTION.Barcode
	FROM 
		CONSIGNMENT,
		MUSICPRODUCT,
		MUSICPRODUCT_CONSIGNMENT,
		PRODUCTDESCRIPTION
	WHERE
		CONSIGNMENT.Id = MUSICPRODUCT_CONSIGNMENT.ConsignmentId AND 
		MUSICPRODUCT.Id = MUSICPRODUCT_CONSIGNMENT.ProductId AND 
		PRODUCTDESCRIPTION.Id = MUSICPRODUCT.ProductDescriptionId AND
		CONSIGNMENT.ConsignmentStatus <> 0 AND
		CONSIGNMENT.ReportingStatus = 0
END;
